apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: simple-server
  name: simple-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: simple-server
  template:
    metadata:
      labels:
        k8s-app: simple-server
      name: simple-server
    spec:
      containers:
        - command:
            - /server/app
          ports:
            - containerPort: 8080
          image: yeqown/simple-server:v1.0.0
          imagePullPolicy: IfNotPresent
          name: server
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
            requests:
              cpu: "0.1"
              memory: 100Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: simple-server
  name: simple-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: simple-server