// Code generated by protoc-gen-go. DO NOT EDIT.
// source: doctor.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Doctor struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Doctor) Reset()         { *m = Doctor{} }
func (m *Doctor) String() string { return proto.CompactTextString(m) }
func (*Doctor) ProtoMessage()    {}
func (*Doctor) Descriptor() ([]byte, []int) {
	return fileDescriptor_5579576f5d887706, []int{0}
}

func (m *Doctor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Doctor.Unmarshal(m, b)
}
func (m *Doctor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Doctor.Marshal(b, m, deterministic)
}
func (m *Doctor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Doctor.Merge(m, src)
}
func (m *Doctor) XXX_Size() int {
	return xxx_messageInfo_Doctor.Size(m)
}
func (m *Doctor) XXX_DiscardUnknown() {
	xxx_messageInfo_Doctor.DiscardUnknown(m)
}

var xxx_messageInfo_Doctor proto.InternalMessageInfo

func (m *Doctor) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Doctor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Doctor) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Doctor)(nil), "celgo.demo.Doctor")
}

func init() { proto.RegisterFile("doctor.proto", fileDescriptor_5579576f5d887706) }

var fileDescriptor_5579576f5d887706 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xc9, 0x4f, 0x2e,
	0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x4e, 0xcd, 0x49, 0xcf, 0xd7,
	0x4b, 0x49, 0xcd, 0xcd, 0x57, 0xb2, 0xe3, 0x62, 0x73, 0x01, 0xcb, 0x09, 0xf1, 0x71, 0x31, 0x65,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc,
	0x89, 0xe9, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x20, 0xa6, 0x13, 0x5b, 0x14, 0x4b,
	0x6e, 0x62, 0x66, 0x5e, 0x12, 0x1b, 0xd8, 0x68, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d,
	0x10, 0xc3, 0x20, 0x6a, 0x00, 0x00, 0x00,
}
