schemaName: sharding_db

dataSources:
  sharding_db_0:
    url: jdbc:mysql://mysql:3306/sharding_db_0?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  sharding_db_1:
    url: jdbc:mysql://mysql:3306/sharding_db_1?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
rules:
  - !SHARDING # 数据分片规则配置
    tables:
      t_user:
        actualDataNodes: sharding_db_${0..1}.t_user_${0..1}
        tableStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: t_user_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
      t_order: # 使用 HINT 分片
        actualDataNodes: sharding_db_${0..1}.t_order_${0..1}
        databaseStrategy:
          hint:
            shardingAlgorithmName: database_hint_inline
        tableStrategy:
          hint:
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    defaultDatabaseStrategy:
      standard:
        shardingColumn: mch_id
        shardingAlgorithmName: database_inline
    defaultTableStrategy:
      none:
    # 分片算法
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: sharding_db_${mch_id % 2}
      database_hint_inline:
        type: INLINE
        props:
          algorithm-expression: sharding_db_${mch_id % 2}
      t_user_inline:
        type: INLINE
        props:
          algorithm-expression: t_user_${user_id % 2}
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: t_order_${user_id % 2}
    # 主键生成器
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 3
