---
graphql:
  max_size: 1048576
nginx_config:
  worker_shutdown_timeout: 240s
  max_pending_timers: 16384
  max_running_timers: 4096
  meta:
    lua_shared_dict:
      prometheus-metrics: 15m
  event:
    worker_connections: 10620
  http:
    access_log_buffer: 16384
    keepalive_timeout: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    client_max_body_size: 0
    send_timeout: 10s
    access_log: logs/access.log
    real_ip_header: X-Real-IP
    access_log_format: |
      "$remote_addr - $remote_user [$time_local] $http_host \"$request\" $status $body_bytes_sent $request_time \"$http_referer\" \"$http_user_agent\" $upstream_addr $upstream_status $upstream_response_time \"$upstream_scheme://$upstream_host$upstream_uri\""
    real_ip_recursive: "off"
    real_ip_from:
      - 127.0.0.1
      - "unix:"
    proxy_ssl_server_name: true
    charset: utf-8
    variables_hash_max_size: 2048
    upstream:
      keepalive_requests: 1000
      keepalive_timeout: 60s
      keepalive: 320
    lua_shared_dict:
      plugin-limit-count: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      ocsp-stapling: 10m
      cas-auth: 10m
      tars: 1m
      ext-plugin: 1m
      access-tokens: 1m
      introspection: 10m
      jwks: 1m
      discovery: 1m
      internal-status: 10m
      prometheus-metrics: 10m
      upstream-healthcheck: 10m
      tracing_buffer: 10m
      plugin-api-breaker: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
      balancer-ewma-locks: 10m
      balancer-ewma-last-touched-at: 10m
      etcd-cluster-health-check: 10m
      plugin-limit-conn: 10m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-req: 10m
    underscores_in_headers: "on"
    access_log_format_escape: default
    enable_access_log: true
  stream_configuration_snippet: |
    # Add custom Nginx stream configuration to nginx.conf.
    # The configuration should be well indented!
  http_end_configuration_snippet: |
    # Add custom Nginx http end configuration to nginx.conf.
    # The configuration should be well indented!
  main_configuration_snippet: |
    # Add custom Nginx main configuration to nginx.conf.
    # The configuration should be well indented!
  http_configuration_snippet: |
    # Add custom Nginx http configuration to nginx.conf.
    # The configuration should be well indented!
  http_server_configuration_snippet: |
    # Add custom Nginx http server configuration to nginx.conf.
    # The configuration should be well indented!
  worker_rlimit_nofile: 20480
  error_log_level: warn
  error_log: logs/error.log
  worker_processes: auto
  http_server_location_configuration_snippet: |
    # Add custom Nginx http server location configuration to nginx.conf.
    # The configuration should be well indented!
  http_admin_configuration_snippet: |
    # Add custom Nginx admin server configuration to nginx.conf.
    # The configuration should be well indented!
  enable_cpu_affinity: false
  stream:
    enable_access_log: false
    access_log: logs/access_stream.log
    access_log_format: |
      "$remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received $session_time" # Customize log format: http://nginx.org/en/docs/varindex.html
    access_log_format_escape: default
    lua_shared_dict:
      lrucache-lock-stream: 10m
      plugin-limit-conn-stream: 10m
      worker-events-stream: 10m
      tars-stream: 1m
      etcd-cluster-health-check-stream: 10m
stream_plugins:
  - ip-restriction
  - limit-conn
  - mqtt-proxy
  - syslog
etcd:
  tls:
    verify: true
  timeout: 30
  host:
    - http://etcd:2379
  watch_timeout: 50
  startup_retry: 2
  prefix: /apisix
plugin_attr:
  inspect:
    delay: 3
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
  server-info:
    report_ttl: 60
  dubbo-proxy:
    upstream_multiplex_count: 32
  skywalking:
    report_interval: 3
    endpoint_addr: http://127.0.0.1:12800
    service_name: APISIX
    service_instance_name: APISIX Instance Name
  log-rotate:
    enable_compression: false
    max_size: -1
    timeout: 10000
    interval: 3600
    max_kept: 168
  opentelemetry:
    collector:
      address: 127.0.0.1:4318
      request_headers:
        Authorization: token
      request_timeout: 3
    resource:
      service.name: APISIX
    trace_id_source: x-request-id
    set_ngx_var: false
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 16
  proxy-mirror:
    timeout:
      read: 60s
      send: 60s
      connect: 60s
  prometheus:
    export_addr:
      port: 9091
      ip: 127.0.0.1
    metric_prefix: apisix_
    enable_export_server: true
    export_uri: /apisix/prometheus/metrics
  zipkin:
    set_ngx_var: false
deployment:
  etcd:
    tls:
      verify: true
    timeout: 30
    host:
      - http://etcd:2379
    watch_timeout: 50
    startup_retry: 2
    prefix: /apisix
  role: traditional
  role_traditional:
    config_provider: etcd
  config_provider: etcd
  admin:
    admin_listen:
      port: 9180
      ip: 0.0.0.0
    admin_api_version: v3
    admin_key_required: false
    admin_key:
      - name: admin
        key: dcEiLKQljuvfBKJQXRSTdWGettxAgnux
        role: admin
    allow_admin:
      - 0.0.0.0/0
    enable_admin_cors: true
apisix:
  proxy_mode: http
  resolver_timeout: 5
  normalize_uri_like_servlet: false
  delete_uri_tail_slash: false
  node_listen:
    - 9080
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: true
  enable_http2: true
  extra_lua_path: ""
  extra_lua_cpath: ""
  proxy_cache:
    cache_ttl: 10s
    zones:
      - name: disk_cache_one
        disk_path: /tmp/disk_cache_one
        cache_levels: "1:2"
        memory_size: 50m
        disk_size: 1G
      - name: memory_cache
        memory_size: 50m
  data_encryption:
    keyring:
      - qeddd145sfvddff3
      - edd1c9f0985e76a2
    enable_encrypt_fields: true
  enable_server_tokens: true
  events:
    module: lua-resty-events
  show_upstream_status_in_response_header: false
  disable_sync_configuration_during_start: false
  enable_control: true
  ssl:
    enable: true
    ssl_protocols: TLSv1.2 TLSv1.3
    listen:
      - enable_http3: false
        port: 9443
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false
  enable_resolv_search_opt: true
  router:
    http: radixtree_host_uri
    ssl: radixtree_sni
  enable_admin: true
plugins:
  - ip2location
  # - real-ip
  # - ai
  # - client-control
  # - proxy-control
  # - request-id
  # - zipkin
  # - ext-plugin-pre-req
  # - fault-injection
  # - mocking
  # - serverless-pre-function
  # - cors
  # - ip-restriction
  # - ua-restriction
  # - referer-restriction
  # - csrf
  # - uri-blocker
  # - request-validation
  # - chaitin-waf
  # - multi-auth
  # - openid-connect
  # - cas-auth
  # - authz-casbin
  # - authz-casdoor
  # - wolf-rbac
  # - ldap-auth
  # - hmac-auth
  # - basic-auth
  # - jwt-auth
  # - jwe-decrypt
  # - key-auth
  # - consumer-restriction
  # - forward-auth
  # - opa
  # - authz-keycloak
  # - proxy-cache
  # - body-transformer
  # - ai-prompt-template
  # - ai-prompt-decorator
  # - proxy-mirror
  # - proxy-rewrite
  # - workflow
  # - api-breaker
  # - limit-conn
  # - limit-count
  # - limit-req
  # - gzip
  # - server-info
  # - traffic-split
  # - redirect
  # - response-rewrite
  # - degraphql
  # - kafka-proxy
  # - grpc-transcode
  # - grpc-web
  # - http-dubbo
  # - public-api
  # - prometheus
  # - datadog
  # - loki-logger
  # - elasticsearch-logger
  # - echo
  # - loggly
  # - http-logger
  # - splunk-hec-logging
  # - skywalking-logger
  # - google-cloud-logging
  # - sls-logger
  # - tcp-logger
  # - kafka-logger
  # - rocketmq-logger
  # - syslog
  # - udp-logger
  # - file-logger
  # - clickhouse-logger
  # - tencent-cloud-cls
  # - inspect
  # - example-plugin
  # - aws-lambda
  # - azure-functions
  # - openwhisk
  # - openfunction
  # - serverless-post-function
  # - ext-plugin-post-req
  # - ext-plugin-post-resp
